Move test report to separate workflow, disable publish for PRs (#1753)

diff --git a/.github/workflows/build_and_publish.yml b/.github/workflows/build_and_publish.yml
--- a/.github/workflows/build_and_publish.yml
+++ b/.github/workflows/build_and_publish.yml
@@ -3,8 +3,10 @@ name: Build and publish
 on:
   pull_request:
     branches:
-      - 'master'
+      - master
   push:
+    branches:
+      - master
     tags:
       - v**
   workflow_dispatch:
@@ -18,12 +20,13 @@ env:
 
 jobs:
   build:
-    name: Build Project
+    name: Build and publish
     runs-on: ubuntu-20.04
     permissions:
       packages: write
       checks: write
-      pull-requests: write
+      actions: write
+      statuses: write
 
     steps:
     - name: Checkout Repo
@@ -68,31 +71,39 @@ jobs:
       run: dotnet build -c Release --no-restore
 
     - name: Test
-      run: dotnet test -c Release --no-build --logger trx --results-directory ./TestResults || exit 0
+      run: dotnet test -c Release --no-build --logger trx --results-directory ./TestResults
 
-    - name: Report tests results
-      uses: NasAmin/trx-parser@v0.2.0
-      id: trx-parser
+    - name: Save test results to artifacts
+      uses: actions/upload-artifact@v3  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
       with:
-        TRX_PATH: ${{ github.workspace }}/TestResults #This should be the path to your TRX files
-        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        name: test-results
+        path: TestResults
+
+    #Rest of the pipeline implies write api privileges and can't be run on PRs
 
     - name: Publish portal
+      if: github.event_name != 'pull_request'
       run: dotnet publish -c Release --no-build ./src/JoinRpg.Portal/JoinRpg.Portal.csproj -p:Version=${{ env.CALCULATED_VERSION }}
 
     - name: Publish migrator
+      if: github.event_name != 'pull_request'
       run: dotnet publish -c Release --no-build ./src/Joinrpg.Dal.Migrate/Joinrpg.Dal.Migrate.csproj -p:Version=${{ env.CALCULATED_VERSION }}
 
     - name: Build portal image
+      if: github.event_name != 'pull_request'
       run: docker build ./src/JoinRpg.Portal --tag ${APP_NAME} --label "runnumber=${GITHUB_RUN_ID}"
 
     - name: Build migrator image
+      if: github.event_name != 'pull_request'
       run: docker build ./src/Joinrpg.Dal.Migrate --tag ${MIGRATOR_NAME} --label "runnumber=${GITHUB_RUN_ID}"
 
     - name: Log in to docker registry
+      if: github.event_name != 'pull_request'
       run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
 
     - name: Push portal image to docker registry
+      if: github.event_name != 'pull_request'
       run: |
         APP_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${APP_NAME}
 
@@ -110,6 +121,7 @@ jobs:
         fi
 
     - name: Push migrator image to docker registry
+      if: github.event_name != 'pull_request'
       run: |
         MIGRATOR_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${MIGRATOR_NAME}
 
